"""add cascad delete

Revision ID: 1337e5651588
Revises: a8d1acdd2280
Create Date: 2022-02-14 12:49:05.662663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1337e5651588'
down_revision = 'a8d1acdd2280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_numbers_room_id_fkey', 'booking_numbers', type_='foreignkey')
    op.create_foreign_key(None, 'booking_numbers', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_numbers', type_='foreignkey')
    op.create_foreign_key('booking_numbers_room_id_fkey', 'booking_numbers', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
