"""add index to 'where' columns

Revision ID: 598149d15caf
Revises: 1337e5651588
Create Date: 2022-02-14 17:29:09.739501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '598149d15caf'
down_revision = '1337e5651588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('booking_numbers_booking_number_key', 'booking_numbers', type_='unique')
    op.create_index(op.f('ix_booking_numbers_booking_number'), 'booking_numbers', ['booking_number'], unique=True)
    op.create_index(op.f('ix_booking_numbers_date_in'), 'booking_numbers', ['date_in'], unique=False)
    op.create_index(op.f('ix_booking_numbers_date_out'), 'booking_numbers', ['date_out'], unique=False)
    op.create_index(op.f('ix_booking_numbers_room_id'), 'booking_numbers', ['room_id'], unique=False)
    op.drop_constraint('rooms_name_key', 'rooms', type_='unique')
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=True)
    op.create_index(op.f('ix_rooms_number_of_seats'), 'rooms', ['number_of_seats'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_number_of_seats'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.create_unique_constraint('rooms_name_key', 'rooms', ['name'])
    op.drop_index(op.f('ix_booking_numbers_room_id'), table_name='booking_numbers')
    op.drop_index(op.f('ix_booking_numbers_date_out'), table_name='booking_numbers')
    op.drop_index(op.f('ix_booking_numbers_date_in'), table_name='booking_numbers')
    op.drop_index(op.f('ix_booking_numbers_booking_number'), table_name='booking_numbers')
    op.create_unique_constraint('booking_numbers_booking_number_key', 'booking_numbers', ['booking_number'])
    # ### end Alembic commands ###
