"""change uuid field

Revision ID: 7b50da07b177
Revises: 5aac749dac54
Create Date: 2022-02-04 15:29:23.201542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b50da07b177'
down_revision = '5aac749dac54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
